# Site settings
title: Tiago Gonçalves | Psicólogo Clínico
description: "A sua saúde é a nossa prioridade"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero:
    hero_img: hero.jpg
    hero_title: Tiago Gonçalves
    hero_description: Psicólogo Clínico

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 91 300 84 60
    emergency: 931 53 234
    email: tvieiragoncalves@gmail.com
    address: Rua de Mosqueiros, Oliveira do Arda - Raiva, Castelo de Paiva

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
